---
site_runtime: NODE_V16
site_config_deployment_artifacts:
  site_config_json: src/phobase/siteConfig.json
  static_dir: dist
site_config_routes:
  static_route: "*"
  not_found_route: "/index.html"
site_config_schema:
  pages:
    - name: Home
      blocks:
        - name: Posts
          views:
            - name: Posts
              columns:
                - name: Name
                  type: TEXT
                - name: Image
                  type: STORE
                - name: Category
                  type: SELECT
                - name: Poster name
                  type: TEXT
                - name: Poster image
                  type: STORE
                - name: Posted at
                  type: DATE_TIME
