---
site_runtime: NODE_V16
site_config_deployment_artifacts:
  site_config_json: src/siteConfig.json
  static_dir: dist
site_config_routes:
  static_route: "*"
  not_found_route: "/index.html"
site_config_schema:
  pages: []
