---
site_runtime: NODE_V16
site_deployment:
  artifacts:
    site_config_file: src/siteConfig.json
    static_dir: dist
site_proxy:
  error_routes:
    - type: NOT_FOUND
      route: "/index.html"
  routes:
    - type: STATIC
      prefix: ""
site_config:
  classes: []
  files: []
  components: []
  pages: []
